Feature-73: password change prompt
atlp-rwanda/ecommerce-app-champions-fe pull request #10
Opened 2023-04-26 11:41 UTC by chrill-christella

what does this PR do?

implement password change prompt

2023-04-28 10:26 UTC, chrill-christella commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be presented with an interface that prompts them to change their passwords every x amount of time](https://trello.com/c/0RP0P8wO/73-users-should-be-presented-with-an-interface-that-prompts-them-to-change-their-passwords-every-x-amount-of-time)

2023-05-01 12:30 UTC, sostene12 reviewed
improve the PR and show means to test the feature

2023-05-02 09:39 UTC, wakaflorien requested changes
- coverage folder must be ignored
- branch name should follow the correct guide.

2023-05-02 09:39 UTC, wakaflorien commented on src/redux/actions/auth.loginActions.js
> +} from '../reducers/auth/loginSlice';
- check this import warning.

2023-05-02 09:39 UTC, wakaflorien commented on src/redux/reducers/rootreducer.js
> +import loginSlice from './auth/loginSlice';
- check this import warning
- make sure build is passing

2023-05-02 09:39 UTC, wakaflorien commented on src/redux/reducers/Auth/loginSlice.js
> +			state.passwordExpired = true;
- everytime the login fails doesn't mean the password is expired. it can easily mean entered credentials are not correct.

2023-05-02 09:39 UTC, wakaflorien commented on src/redux/reducers/Auth/loginSlice.js
> +		passwordExpired: (state) => {
- change the rest of the state.

2023-05-02 14:49 UTC, sostene12 reviewed
- I've seen the popup as your PR said, but I'm not being redirected to where i will reset the password, and i don't see the email

2023-05-03 07:42 UTC, sostene12 requested changes

2023-05-03 07:42 UTC, sostene12 commented on coverage/components/Button/GoogleButton.jsx.html
please remove the coverage folder

2023-05-03 07:42 UTC, sostene12 commented on coverage/coverage-final.json
ignore the coverage folder in .gitignore

2023-05-03 08:09 UTC, sostene12 approved these changes

2023-05-03 10:19 UTC, closed without merging