#72 Implement  Two factor authentication for Vendor and Admin
atlp-rwanda/ecommerce-app-champions-fe pull request #11
Opened 2023-04-26 13:39 UTC by Shumba250

#### What does this PR do?

- Implement a two-factor authentication page for vendor login
#### Description of Task to be completed

- Implement a responsive two-factor authentication page
- Process OTP and redirect the vendor to the dashboard
- Validate the OTP input field
#### How should this be manually tested?

- clone the repo using git clone repo's URL
- change branch git checkout ft-two-factor-auth
- create .env file and paste variables from .env.example
- run npm install 
- run npm run dev
- signup a vendor and login
- Copy the OTP sent to your email and paste it in the input filed

2023-04-27 07:51 UTC, Shumba250 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Seller auth & Two Factor Authentication for Sellers](https://trello.com/c/K58Vpe6U/72-seller-auth-two-factor-authentication-for-sellers)

2023-05-01 12:50 UTC, sostene12 reviewed
<img width="1280" alt="Screenshot 2023-05-01 at 14 49 06" src="https://user-images.githubusercontent.com/88575509/235453860-1c7edc01-b6b7-4912-9531-468ea723d23e.png">
this card is soo big, if you can reduce it

2023-05-03 07:34 UTC, sostene12 requested changes

2023-05-03 07:34 UTC, sostene12 commented on coverage/components/Auth/Input.jsx.html
i suggest you don't push coverage folder, please ignore it

2023-05-03 07:34 UTC, sostene12 commented on src/pages/index.jsx
consider using app.jsx as the main file of routes

2023-05-03 07:34 UTC, sostene12 commented on src/redux/actions/authAction.js
it's not a good practice to use browser storage mean, if it is local storage stick with it only, or stick to using cookies only

2023-05-04 05:32 UTC, sostene12 approved these changes

2023-05-04 06:14 UTC, Luciefifi approved these changes

2023-05-04 06:22 UTC, chrill-christella approved these changes

2023-05-04 08:56 UTC, wakaflorien approved these changes

2023-05-04 09:28 UTC, merged