Ft reset password
atlp-rwanda/ecommerce-app-champions-fe pull request #12
Opened 2023-04-26 14:17 UTC by Luciefifi

2023-05-01 12:34 UTC, sostene12 reviewed
running the branch, but nothing is being rendered

2023-05-02 07:52 UTC, wakaflorien requested changes
- rename your branch according to the guide
- add coverage to `.gitignore`

2023-05-02 07:52 UTC, wakaflorien commented on src/pages/ResetPassword.jsx
> +const override = css`
- there is no need of using `@emotion/react` for styling, we have tailwind for that

2023-05-02 07:52 UTC, wakaflorien commented on src/pages/ResetPassword.jsx
> +			timer = setTimeout(() => navigate('/login'), 5000); // Redirect to login page after 5 seconds
- it recommended to use `redirect` instead of     useNavigate` hook.

2023-05-02 07:52 UTC, wakaflorien commented on src/pages/ResetPassword.jsx
> +					</div> */}
- use `className` prop to set input styles keeping in mind input width and height should be the same.
- check the values of left and right side division of the screen also.

2023-05-02 07:52 UTC, wakaflorien commented on src/pages/ResetPassword.jsx
> +					<Button
- check common size of button for uniformity.

2023-05-02 07:52 UTC, wakaflorien commented on src/pages/ForgotPassword.jsx
> +						placeholder="Email"
- check common size of the button.
- be consistent with the `padding` and `margins`

2023-05-02 07:52 UTC, wakaflorien commented on src/tests/resetPassword.test.jsx
> +		expect(component).toBeInTheDocument();
- Add more test scenarios other than component `render` and element `toBeInTheDocument`.

2023-05-02 07:52 UTC, wakaflorien commented on src/tests/forgotPassword.test.jsx
> +	it('should display a "back to login" link', () => {
- Add more test scenarios other than component render and element toBeInTheDocument.

2023-05-02 14:07 UTC, sostene12 requested changes

2023-05-02 14:07 UTC, sostene12 commented on coverage/api/index.html
ignore coverage folder

2023-05-02 14:07 UTC, sostene12 commented on coverage/pages/HomePage.jsx.html
- please put coverage folder in gitignore, and don't push it

2023-05-02 14:07 UTC, sostene12 commented on src/components/Button/PasswordButton.jsx
change the styles of the button, remove the static styles and let all styles(classNames) be passed in props. 
```
<button type="submit" className={className}>
			{label}
		</button>
```

2023-05-02 14:07 UTC, sostene12 commented on src/pages/ForgotPassword.jsx
please remove css, and use tailwind only

2023-05-02 14:07 UTC, sostene12 commented on src/pages/index.jsx
may be remove that comments and delete this file use app file for routes

2023-05-02 14:07 UTC, sostene12 commented on src/redux/reducers/Auth/ResetPasswordSlice.jsx
```http://localhost:3000/api/user/resetpassword/${token}` this is not a good practice, plase use the url from env 
`import varkeys from '../constants/keys';

const url = varkeys.APP_URL;
you can do like this  ${url}/api/user/resetpassword/${token}`
`

2023-05-02 14:07 UTC, sostene12 commented on src/redux/reducers/auth/ForgotSlice.jsx
follow the above comment , and remove that url of localhost and user the link from env, in addition use the deployed url

2023-05-02 14:07 UTC, sostene12 commented on src/utilis/testUtilis.jsx
i thinks this file is no longer necessary , hence this contents are in /test/setup.tests

2023-05-02 14:07 UTC, sostene12 commented on src/tests/resetPassword.test.jsx
also change the file namings of those reducers

2023-05-03 07:25 UTC, sostene12 requested changes

2023-05-03 07:25 UTC, sostene12 commented on src/components/Button/PasswordButton.jsx
i suggest we use single button components, where the styles will be passed in the props

2023-05-03 07:25 UTC, sostene12 commented on src/redux/reducers/rootreducer.js
you can changer the file extensions of the files in redux folder from .jsx to .js

2023-05-03 11:02 UTC, closed without merging