#69 feature: Login with Email and Password
atlp-rwanda/ecommerce-app-champions-fe pull request #14
Opened 2023-04-26 22:02 UTC by oliviertech212

## What does this PR do:
- create login react component
- design login UI
- test ui component
## Descriptions
- Login with Email and Password
## How should this be manually tested?
- clone the repo by ` git clone  https://github.com/atlp-rwanda/ecommerce-app-champions-fe.git`
- change branch git checkout `ft-signin`
- create .env file and paste variables from .env.example
- run `npm run dev`
-  copy url link into your browser `url/Login`
<img width="1244" alt="Screenshot 2023-04-26 at 23 26 32" src="https://user-images.githubusercontent.com/89464364/234711916-e8ff02e6-1e0d-42c4-a1b7-48ef5a66c932.png">

-  run test `npm run test`
- run coverage `npm run coverage`
<img width="1440" alt="Screenshot 2023-04-26 at 23 25 38" src="https://user-images.githubusercontent.com/89464364/234712255-5fc6f6f5-fdf4-41a7-b363-afa5223f13eb.png">

## Trello card #69

2023-04-26 22:07 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to Login with Email and Password](https://trello.com/c/LRMtWOCV/69-users-should-be-able-to-login-with-email-and-password)

2023-05-01 11:43 UTC, sostene12 reviewed
- login with Google is not working

2023-05-01 11:43 UTC, sostene12 commented on vite.config.js
please recall on the commented codes  and change that

2023-05-01 14:43 UTC, oliviertech212 commented on vite.config.js
create .env file and paste variables from .env.example

2023-05-01 16:13 UTC, chrill-christella approved these changes

2023-05-02 07:22 UTC, wakaflorien requested changes
- rename the branch to follow the the guide
- add `coverage` directory in `.gitignore`

2023-05-02 07:22 UTC, wakaflorien commented on src/pages/Login.jsx
> +							className="appearance-none py-2 px-2 my-2 rounded-md w-11/12"
- This input seems to be wider than the ones signup.

2023-05-02 07:22 UTC, wakaflorien commented on src/redux/reducers/Auth/loginSlice.js
> +			state.user = '';
- use `null` instead of empty string.

2023-05-02 07:22 UTC, wakaflorien commented on src/pages/Login.jsx
> +			if (user?.data?.others?.RoleId === 1) return navigate('/admin');
- better to use `redirect` than this `useNavigate` hook.

https://reactrouter.com/en/main/fetch/redirect

2023-05-02 07:22 UTC, wakaflorien commented on src/redux/actions/auth.loginActions.js
> +import Cookies from 'js-cookie';
- address eslint errors on this line.

2023-05-02 20:23 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [WIP - Users should be able to Login via Google](https://trello.com/c/V4aK1Xhh/68-wip-users-should-be-able-to-login-via-google)

2023-05-03 07:03 UTC, wakaflorien approved these changes

2023-05-03 07:03 UTC, wakaflorien commented on vite.config.js
> +// import { defineConfig } from 'vite';
- remove these commented line @oliviertech212

2023-05-03 07:04 UTC, wakaflorien requested changes
- rename the branch

2023-05-03 07:38 UTC, sostene12 approved these changes

2023-05-03 07:53 UTC, Shumba250 approved these changes

2023-05-03 08:29 UTC, closed without merging