#67 fix: fixing signup feature
atlp-rwanda/ecommerce-app-champions-fe pull request #16
Opened 2023-05-02 16:50 UTC by sostene12

#### What does this PR do?
- user signup with email and password ( fixing thesignup feature) and work on review
#### Description of Task to be completed
- implement the initial states fix in redux slices
- implement the default props in the components
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout fix-signup
- create .env file  and paste variables from .env.example
- run `npm run dev`
- navigate to the vendor for vendor signup or buyer for buyer signup
#### What are the relevant pivotal tracker stories?
- ![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able Signup/Register to the E-commerce App and verify email](https://trello.com/c/gJH8dzJ0)

2023-05-03 07:07 UTC, wakaflorien requested changes
- check the ci build

2023-05-03 16:23 UTC, Shumba250 approved these changes

2023-05-04 04:52 UTC, chrill-christella approved these changes

2023-05-04 05:51 UTC, wakaflorien approved these changes

2023-05-04 05:51 UTC, merged