#59 chore: Setup Redux
atlp-rwanda/ecommerce-app-champions-fe pull request #2
Opened 2023-04-18 19:13 UTC by sostene12

#### What does this PR do?
- implement Redux Toolkit
#### Description of Task to be completed
- implement redux toolkit setup
- implement test single sample endpoint of getting all products
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ch-setup-redux
- create .env file  and paste variables from .env.example
- run `npm run dev`
#### What are the relevant pivotal tracker stories?
- ![](https://github.trello.services/images/mini-trello-icon.png) [Setup Redux](https://trello.com/c/XwQ5ryHv)

2023-04-19 10:08 UTC, sostene12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Redux](https://trello.com/c/XwQ5ryHv/59-setup-redux)

2023-04-19 10:29 UTC, nicele08 requested changes
@sostene12 Well done, I can see the code is clean. Just put the api link into `.env.local` file.

2023-04-19 10:29 UTC, nicele08 commented on src/constants/url.js
> +export default url;
@sostene12 Vite exposes env variables on the special `import.meta.env` object so we can put the api url into `.env.local` file. Kindly follow this [link](https://vitejs.dev/guide/env-and-mode.html) for Env Variables and Modes

2023-04-19 13:28 UTC, wakaflorien reviewed
- good job on the whole setup. though i would advise you create directories for reducers and slices because they will probably be more than one.

2023-04-19 17:02 UTC, sostene12 commented
> * good job on the whole setup. though i would advise you create directories for reducers and slices because they will probably be more than one.

done

2023-04-19 17:02 UTC, sostene12 commented
> * good job on the whole setup. though i would advise you create directories for reducers and slices because they will probably be more than one.

2023-04-19 17:02 UTC, sostene12 commented
> > * good job on the whole setup. though i would advise you create directories for reducers and slices because they will probably be more than one.

done

2023-04-19 17:16 UTC, nicele08 requested changes

2023-04-19 17:16 UTC, nicele08 commented on .env.example
> +VITE_BASE_URL=https://ecommerce-champions.onrender.com
This is good

2023-04-19 17:16 UTC, nicele08 commented on src/constants/url.js
> +const url = "https://ecommerce-champions.onrender.com";
@sostene12 why do we still have this hard-coded value? I recommend you to rename the `url.js` to some thing like `keys.js` and then declare the `API_URL` there.

Hint:
```javascript
const keys = {
  API_URL: import.meta.VITE_BASE_URL
}
export default keys;
```

2023-04-19 17:16 UTC, nicele08 commented on src/redux/reducers/product/productSlice.js
> +const url = import.meta.env.VITE_BASE_URL;
@sostene12 As I said in the `url.js` file, please put this into the constants so that other developers can access it.

2023-04-19 17:39 UTC, wakaflorien approved these changes

2023-04-19 17:50 UTC, wakaflorien approved these changes

2023-04-19 17:51 UTC, wakaflorien approved these changes

2023-04-19 17:55 UTC, nicele08 approved these changes

2023-04-20 06:58 UTC, oliviertech212 approved these changes

2023-04-20 10:20 UTC, Luciefifi approved these changes

2023-04-20 10:55 UTC, Shumba250 approved these changes

2023-04-20 11:07 UTC, merged