#77 feature :Create the delete product feature
atlp-rwanda/ecommerce-app-champions-fe pull request #20
Opened 2023-05-04 19:32 UTC by patsicko

- Create a model with a dialog box asking  a vendor if he/she is sure of deleting a product [Finishes #CP-77]
- #### What does this PR do?
- Create the delete product feature
#### Description of Task to be completed
- Create a model with a dialog box asking  a vendor if he/she is sure of deleting a product
- Implement the feature for deleting a product in a seller's collection
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ft-edit-profile-78
- create .env file  and paste variables from .env.example
- run `npm run dev`
- navigate to Vendor signup
-  Signup get a password from your email and use it for login
-  Get authenticated via two factor auth
- You will be redirected to vendor's dashboard and have access on vendor's product
-  Click on delete button, a model with dialogue box will be displayed
#### What are the relevant pivotal tracker stories?
https://trello.com/c/ADRXylJo/77-a-seller-should-be-able-to-delete-a-specific-item-from-their-collection

2023-05-04 19:32 UTC, patsicko commented
![](https://github.trello.services/images/mini-trello-icon.png) [A seller should be able to delete a specific item from their collection](https://trello.com/c/ADRXylJo/77-a-seller-should-be-able-to-delete-a-specific-item-from-their-collection)

2023-05-08 07:11 UTC, wakaflorien requested changes

2023-05-08 07:11 UTC, wakaflorien commented on src/api/userApi.js
> +// export const deleteProduct = (productId, token) => {
- remove all these unused lines codes @patsicko

2023-05-08 07:11 UTC, wakaflorien commented on src/components/product/DeleteProduct.jsx
> +							<button
- we have a button component that can be used instead of recreating button element everytime.

2023-05-08 07:11 UTC, wakaflorien commented on tailwind.config.js
> +		// fontSize: {
- if these lines are not being used you better remove it

2023-05-08 12:01 UTC, sostene12 requested changes

2023-05-08 12:01 UTC, sostene12 commented on src/components/dashboard/products.jsx
remove the comments

2023-05-08 12:01 UTC, sostene12 commented on src/components/dashboard/products.jsx
we have a button components, you can use that instead of using the other

2023-05-08 15:46 UTC, Luciefifi approved these changes

2023-05-08 17:36 UTC, sostene12 approved these changes

2023-05-09 04:57 UTC, wakaflorien approved these changes

2023-05-09 04:57 UTC, merged