#78Feature: seller should be able to view a specific item
atlp-rwanda/ecommerce-app-champions-fe pull request #21
Opened 2023-05-05 05:10 UTC by chrill-christella

2023-05-14 06:12 UTC, Luciefifi reviewed
when I click on that view icon , I am not seeing anything . please check that

2023-05-14 12:07 UTC, wakaflorien requested changes
### Blank page whenever i try to view product as a vendor make sure you solve it.

![image](https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/48131185/b142f147-ec97-488c-b514-186d6ceedf15)

2023-05-15 15:42 UTC, sostene12 approved these changes

2023-05-15 15:53 UTC, Luciefifi approved these changes

2023-05-15 16:18 UTC, oliviertech212 requested changes
<img width="1074" alt="Screenshot 2023-05-15 at 18 13 58" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/89464364/c8e5cfb8-4fa8-438e-9373-9ba800bb6ac6">
make a product image to have the same. width   and height

2023-05-15 16:48 UTC, oliviertech212 approved these changes

2023-05-15 19:32 UTC, wakaflorien approved these changes

2023-05-16 18:44 UTC, merged