#75 feature: A seller should be able to create items
atlp-rwanda/ecommerce-app-champions-fe pull request #23
Opened 2023-05-05 14:37 UTC by oliviertech212

## What does this PR do:
- A seller should be able to create/add items
## Descriptions
- create form to enter item details
- implement Reduxtoolkit
- design UI
## How should this be manually tested?
- clone the repo by ` git clone  https://github.com/atlp-rwanda/ecommerce-app-champions-fe.git`
- change branch git checkout `ft-create-product-cp-75`
- create `.env `file and paste variables from `.env.example`
- run `npm run dev`
-  copy URL link into your browser `URL/Login`
-  login as `vendor  or seller`
## Trello card #75

2023-05-05 14:41 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [A seller should be able to create/add items](https://trello.com/c/LlHWmdn5/75-a-seller-should-be-able-to-create-add-items)

2023-05-08 06:35 UTC, wakaflorien approved these changes

2023-05-08 12:12 UTC, sostene12 requested changes
- first, clear the form after the creation of the product,
- you can hide the modal after creation of the product
- 
<img width="1280" alt="Screenshot 2023-05-08 at 14 07 50" src="https://user-images.githubusercontent.com/88575509/236819880-e421378d-4efe-43aa-82cc-1e39f789af5b.png">
also it is better if you put that modal in the center
last, you have to see the product listed on the dashboard after creation

2023-05-08 12:12 UTC, sostene12 commented on src/components/Button/Button.jsx
why can't you use single button , and pass different class names depending on what you want

2023-05-08 21:11 UTC, sostene12 approved these changes

2023-05-09 03:45 UTC, Luciefifi approved these changes

2023-05-09 04:19 UTC, merged