#76 API to update product from seller collection
atlp-rwanda/ecommerce-app-champions-fe pull request #25
Opened 2023-05-09 12:31 UTC by Luciefifi

# What does this PR do

A seller should be able to update a product from his/her collection

# Description of Task to be completed
Create a model of updating a product
Implement the feature for updating a product in a seller's collection

# How should this be manually tested?
clone the repo using git clone repo's URL
change branch git checkout ft-update-products-cp-76
create .env file and paste variables from .env.example
run npm run dev
navigate to Vendor signup
Signup get a password from your email and use it for login
Get authenticated via two factor auth
You will be redirected to vendor's dashboard and have access on vendor's product
Click on edit icon, a model with dialogue box will be displayed

# Relevant pivotal tracker user story
#76

2023-05-09 15:23 UTC, wakaflorien requested changes
- you can cancel an update in case you change your mind.
- add a way to remove and change images

2023-05-09 15:23 UTC, wakaflorien commented on src/redux/reducers/rootreducer.js
> +	update,
follow the same import format to avoid confusion

2023-05-09 15:23 UTC, wakaflorien commented on src/redux/reducers/product/updateProductSlice.js
> +export const updateProduct = createAsyncThunk(
- separate api logic into actions directory instead

2023-05-09 15:23 UTC, wakaflorien commented on src/pages/vendorDashboard.jsx
> +				<Products setIsOpen={setIsOpen} />
- remove this blank space here.

2023-05-09 15:47 UTC, sostene12 reviewed
i don't know why they are telling me that I'm not authorized since I'm logged in as a vendor

2023-05-10 06:09 UTC, oliviertech212 approved these changes

2023-05-10 06:42 UTC, wakaflorien requested changes
- getting undefined trying to update.

![image](https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/48131185/f121dacd-52bf-4c4a-bfbb-889940ef996a)

2023-05-10 13:07 UTC, patsicko approved these changes

2023-05-10 21:28 UTC, sostene12 approved these changes

2023-05-11 07:08 UTC, wakaflorien approved these changes

2023-05-11 07:09 UTC, merged