A
atlp-rwanda/ecommerce-app-champions-fe pull request #28
Opened 2023-05-10 16:11 UTC by Luciefifi

2023-05-15 06:54 UTC, oliviertech212 reviewed
<img width="1074" alt="Screenshot 2023-05-15 at 08 31 09" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/89464364/3a9a3083-6757-4e10-a5c9-7fe03d0298d7">

2023-05-15 13:36 UTC, wakaflorien approved these changes

2023-05-15 15:50 UTC, oliviertech212 requested changes
please change add button color for consistency   and prevent redirect to cart becouse you can add more different products.

2023-05-15 15:58 UTC, chrill-christella approved these changes

2023-05-15 16:07 UTC, sostene12 approved these changes

2023-05-16 11:16 UTC, oliviertech212 approved these changes

2023-05-16 15:57 UTC, merged