#88 feature: A buyer should be able to delete product and clear cart
atlp-rwanda/ecommerce-app-champions-fe pull request #29
Opened 2023-05-11 07:30 UTC by oliviertech212

## What does this PR do?
- buyer should be able to clear cart and update total
## Description of Task to be completed
- implement Reduxtoolkit
- clear buyer's cart
- remove single item from cart
- update total

## How should this be manually tested?
- clone the repo `git clone https://github.com/atlp-rwanda/ecommerce-app-champions-fe.git`
- checkout to `ft-clear-cart-cp-88`
- create `.env `file and paste variables from `.env.example`
- install the packages by `npm install`
- start the server  `npm run dev`
- login in swagger documentation as a buyer. to add product to cart
-  login as `buyer`
- navigate to `cart` 
<img width="1131" alt="Screenshot 2023-05-11 at 08 48 15" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/89464364/bf67623f-7365-4d92-bf3a-951a4521be2f">
-then you can remove single product or clear cart. to remove all product

![image](https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/89464364/ea2f2e57-1225-4e7b-b53e-6e48c5e1a5c6)

## Trello card 88

2023-05-11 07:46 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [A buyer should be able to clear their cart](https://trello.com/c/7UmUtmtE/88-a-buyer-should-be-able-to-clear-their-cart)

2023-05-11 07:53 UTC, wakaflorien requested changes
- when the cart is empty shipping still show $5

![image](https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/48131185/f741d705-61eb-45e2-ba14-3c436c62206d)

2023-05-11 08:03 UTC, sostene12 requested changes
- when i click on remove product from the cart, it does not work instead it loads clear cart button

2023-05-11 08:03 UTC, sostene12 commented on src/components/cart/CartCheckout.jsx
remove coments

2023-05-11 08:03 UTC, sostene12 requested changes
- when i click on remove product from the cart, it does not work instead it loads clear cart button

2023-05-11 08:03 UTC, sostene12 requested changes
- when i click on remove product from the cart, it does not work instead it loads clear cart button

2023-05-11 08:03 UTC, sostene12 requested changes
- when i click on remove product from the cart, it does not work instead it loads clear cart button

2023-05-11 08:58 UTC, patsicko approved these changes

2023-05-11 15:59 UTC, wakaflorien requested changes
- Hide the checkout/side card when the cart is empty

2023-05-11 21:43 UTC, wakaflorien approved these changes

2023-05-12 06:39 UTC, sostene12 reviewed
@oliviertech212 you can not display the loader when there is no token, so the user is not logged in you can redirect to login or display other thinks.

2023-05-12 11:21 UTC, sostene12 approved these changes

2023-05-12 14:37 UTC, merged