#65 chore: Configure ESLint and Git Pre commit hook
atlp-rwanda/ecommerce-app-champions-fe pull request #3
Opened 2023-04-18 21:45 UTC by oliviertech212

## what does this PR do?
- install eslint,prettier,husky dependencies
- configure eslint
- configure prettier
- integrate prettier with eslint
- implement Git pre commit hook
## Descriptions
Configure ESLint and Git Pre commit hook to run tests and ESlint format before commits
## How this should be manually tested:
- clone this repo `git clone https://github.com/atlp-rwanda/ecommerce-app-champions-fe.git`
- checkout to `ch-setup-eslint-pre-commit`
- install the packages by `npm install`
- to test eslint and pre-commit `create file inside src/.  with .js  ` once you done copy code from `App.jsx`  and paste it into your `.js` file 
-  in your terminal  run git command ` git add .` and then try `git commit -m " your message"` you will see how we run lint script to check errors and format script to format our code if any error is found the commit process will be aborted

<img width="1440" alt="Screenshot 2023-04-18 at 22 36 27" src="https://user-images.githubusercontent.com/89464364/232911406-1f5e2cd9-19b7-4898-b176-7b00ca3c64c0.png">

## Trello CARD #65

2023-04-18 21:48 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Configure ESLint and Git Pre commit hook to run tests and ESlint format before commits](https://trello.com/c/QvzrC7JP/65-configure-eslint-and-git-pre-commit-hook-to-run-tests-and-eslint-format-before-commits)

2023-04-19 18:05 UTC, wakaflorien approved these changes

2023-04-19 18:13 UTC, wakaflorien approved these changes, later dismissed
- add more file extensions beacause i created a `.jsx` and it went through 
- add (`.jsx, ts, tsx`) too

2023-04-19 18:18 UTC, wakaflorien requested changes
- add more file extensions beacause i created a `.jsx` and it went through 
- add (`.jsx, ts, tsx`) too

2023-04-20 06:34 UTC, wakaflorien approved these changes

2023-04-20 07:18 UTC, sostene12 approved these changes

2023-04-20 09:24 UTC, Luciefifi approved these changes

2023-04-20 10:58 UTC, Shumba250 approved these changes

2023-04-20 12:44 UTC, merged