#83 Feature- implement notification panel
atlp-rwanda/ecommerce-app-champions-fe pull request #32
Opened 2023-05-12 18:21 UTC by Shumba250

#### What does this PR do?
The notifications panel displays a user's notifications and prompts them to take action when they interact with notification icon
#### Description of Task to be completed

- The notifications pane should open up when a user clicks on the icon. It should contain a list of notifications
#### How should this be manually tested?
clone the repo using git clone repo's URL
change branch git ft- implement notification panel
create .env file and paste variables from .env.example
run npm run dev
login as a vendor
You should be redirected to the dashboard
click on the notification icon and you should be able to see the notification

2023-05-12 18:22 UTC, Shumba250 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement notifications pane](https://trello.com/c/6O2pHIzb/83-implement-notifications-pane)

2023-05-15 15:49 UTC, sostene12 approved these changes
<img width="1260" alt="Screenshot 2023-05-15 at 17 50 04" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/88575509/0d11274d-d513-4f45-9211-2164dc16a695">
the notifications are working, when i make some action, but the style of products are not verywell, consider improving it

2023-05-15 16:13 UTC, patsicko approved these changes

2023-05-15 16:40 UTC, wakaflorien requested changes

2023-05-15 16:40 UTC, wakaflorien commented on vite.config.js.timestamp-1684135706373-7f1bd4242e6e6.mjs
> +//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsidml0ZS5jb25maWcuanMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImNvbnN0IF9fdml0ZV9pbmplY3RlZF9vcmlnaW5hbF9kaXJuYW1lI
- check the vite config file.js the commented section

2023-05-15 16:40 UTC, wakaflorien commented on src/main.jsx
> +	'Mgo+DSMBaFt+QHJqVk1mQ1JbdF9AXnNNdFB3T2Zebz4Nf1dGYl9RQXZbQ1tgSHtUf0xnWQ==;Mgo+DSMBPh8sVXJ1S0R+X1pCaVxdX2NLfUNyT2BYdVt3ZDU7a15RRnVfR11nSHhQd0BrWX5ecA==;ORg4AjUWIQA/Gnt2VFhiQlJPcEBBQmFJfFBmQWlaflR1c0U
-  ass license to .env file

2023-05-15 19:48 UTC, wakaflorien approved these changes

2023-05-15 19:49 UTC, merged