#82 Feature:  Search for a product
atlp-rwanda/ecommerce-app-champions-fe pull request #33
Opened 2023-05-13 09:48 UTC by Luciefifi

# What does this PR do
Users should be able to search for product

2023-05-14 12:16 UTC, wakaflorien requested changes
- after clearing the search you should automatically get all products list back
- Typing in small script products with the same name doesn't come. it should not be case sensitive
- the search input height must be equal to that one of the search button

2023-05-15 05:45 UTC, Shumba250 requested changes
shouldn't this supposed to be on the landing page where a buyer has an option of searching for different products ,

2023-05-15 10:51 UTC, Luciefifi commented
> shouldn't this supposed to be on the landing page where a buyer has an option of searching for different products ,

search product is a component that can be rendered in any page , i used that  page because it is what i had

2023-05-15 15:53 UTC, Shumba250 approved these changes

2023-05-15 15:59 UTC, chrill-christella approved these changes

2023-05-15 16:01 UTC, oliviertech212 approved these changes

2023-05-15 16:20 UTC, sostene12 approved these changes

2023-05-15 16:21 UTC, wakaflorien approved these changes

2023-05-16 14:47 UTC, merged