#92 feature:  A buyer should be able to checkout and pay
atlp-rwanda/ecommerce-app-champions-fe pull request #34
Opened 2023-05-14 13:49 UTC by oliviertech212

## What does this PR do?
- a buyer should be able to checkout and pay
## Description of Task to be completed
- implement Reduxtoolkit. for checkout and payment 
- design a successful payment ui component

## How should this be manually tested?
- clone the repo `git clone https://github.com/atlp-rwanda/ecommerce-app-champions-fe.git`
- checkout to ` ft-create-payment-cp-92`
- create `.env `file and paste variables from `.env.example`
- install the packages by `npm install`
- start the server  `npm run dev`
-  login as `buyer`
- add product to `cart` 
- click on `checkout button`

<img width="815" alt="Screenshot 2023-05-14 at 09 17 06" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/89464364/31727484-4fb9-4a40-a084-060afcafd4bd">

## Trello card 92

2023-05-14 13:51 UTC, oliviertech212 commented
![](https://github.trello.services/images/mini-trello-icon.png) [A buyer should be able to checkout and pay](https://trello.com/c/02jj0Oz0/92-a-buyer-should-be-able-to-checkout-and-pay)

2023-05-15 04:12 UTC, Luciefifi reviewed
can you please give us more details about testing this????

2023-05-15 05:42 UTC, Shumba250 requested changes
work on the success page, it would be better if you design a detailed page or a receipt that contains payment info instead of a json

2023-05-15 15:58 UTC, Shumba250 approved these changes

2023-05-15 16:04 UTC, chrill-christella approved these changes

2023-05-15 16:24 UTC, sostene12 approved these changes

2023-05-15 16:44 UTC, wakaflorien approved these changes

2023-05-17 08:05 UTC, Luciefifi approved these changes

2023-05-18 15:45 UTC, merged