#98 feature: mark all notifications as read
atlp-rwanda/ecommerce-app-champions-fe pull request #39
Opened 2023-05-18 05:26 UTC by chrill-christella

fetch mark all endpoint
implement mark all notifications button
[finishes]

2023-05-21 07:22 UTC, sostene12 requested changes
@chrill-christella  the action that i can perform can be based on the products, and there are no products that are being rendered. you can look into it and change that

second, it is not good to wrap Navigation to login and signup, reset and other places in which that navigation is not needed, change that

2023-05-22 03:34 UTC, Luciefifi reviewed
To make it easy for the reviewer , change the branch name to the branch you are working in

2023-05-26 11:01 UTC, sostene12 requested changes
<img width="1280" alt="Screenshot 2023-05-26 at 12 41 35" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/88575509/e96e99eb-ab45-4ad3-ae3c-ad1f37032fb6">

seems like the styles are not looking good

2023-05-26 16:51 UTC, sostene12 approved these changes

2023-05-26 18:57 UTC, oliviertech212 approved these changes

2023-05-28 03:40 UTC, Luciefifi approved these changes

2023-05-28 09:28 UTC, Shumba250 approved these changes

2023-05-28 15:20 UTC, wakaflorien approved these changes

2023-05-28 15:20 UTC, merged