#64 chore: vitest-setup
atlp-rwanda/ecommerce-app-champions-fe pull request #4
Opened 2023-04-18 21:55 UTC by patsicko

# What this PR do
- Setup vitest for testing
# Description of the task 
- Install vitest and other related dependances
- Configure vite to use jsdom for testing
- Add test in package.json scripts to run test 
# How should this be manually tested?
- clone the repo using git clone repo
- change branch by running git checkout ch-vitest-setup
- install dependencies by npm install
- run npm run test passed tests and coverage will be displayed on CLI

2023-04-18 22:01 UTC, patsicko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup tests](https://trello.com/c/LIEwrHcP/61-setup-tests)

2023-04-19 07:23 UTC, oliviertech212 approved these changes

2023-04-19 09:06 UTC, Shumba250 approved these changes

2023-04-19 09:14 UTC, Shumba250 requested changes
the coverage always shows 100% even if the tests fail. try solving it

2023-04-19 10:51 UTC, wakaflorien approved these changes

2023-04-19 10:53 UTC, sostene12 requested changes

2023-04-19 10:53 UTC, sostene12 commented on src/tests/App.test.jsx
- even if the text is wrong , it still passes

2023-04-19 11:00 UTC, wakaflorien requested changes
- add vitest ui for better visual display
- add a separate test:run command without coverage 
```
   "test:ui": "vitest --ui",
    "test:run": "vitest run",
``` 
something like this.

2023-04-20 16:14 UTC, wakaflorien approved these changes

2023-04-20 16:36 UTC, sostene12 approved these changes

2023-04-20 17:55 UTC, Shumba250 approved these changes

2023-04-24 06:06 UTC, merged