(feat):Track order status
atlp-rwanda/ecommerce-app-champions-fe pull request #42
Opened 2023-05-18 21:54 UTC by patsicko

- #### What does this PR do?
-  Track order of bought products
#### Description of Task to be completed
- Create a track order ui
- Implement the feature that enable a buyer to track order status of products bought
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ft-track-order-cp-96
- create .env file  and paste variables from .env.example
- run `npm run dev`
- navigate to homepage
-  Signup get a password from your email and use it for login as a buyer
- Order a product 
- Click on orders
#### What are the relevant pivotal tracker stories?
https://trello.com/c/L4W58bmE/96-a-buyer-should-be-able-to-track-their-order-status

2023-05-22 13:17 UTC, sostene12 approved these changes

2023-05-22 13:34 UTC, Shumba250 approved these changes

2023-05-22 14:03 UTC, Luciefifi approved these changes

2023-05-23 19:23 UTC, wakaflorien requested changes
- When you click on buy now you get 404

![image](https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/48131185/93516f0d-d91b-4206-a9c5-45c41e8ddc26)

2023-05-24 08:05 UTC, wakaflorien approved these changes

2023-05-24 08:05 UTC, merged