#56 fix: Live chat for a vendor #49
atlp-rwanda/ecommerce-app-champions-fe pull request #45
Opened 2023-05-24 09:36 UTC by patsicko

- #### What does this PR do?
-  Fix bug on live chat for vendor 
#### Description of Task to be completed
GIVEN the vendor is online
When they open the chat tab
THEN they should be able to post a public chat

GIVEN the vendor
When they post a chat
THEN it should be able to be echoed to all online users in realtime.

#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout fix-chat
- create .env file  and paste variables from .env.example
- run `npm run dev`
- navigate to homepage
-  Signup get a password from your email and use it for login
- Click chat button to start chating
#### What are the relevant pivotal tracker stories?
https://trello.com/c/EqD9Iv5R/84-users-should-be-able-to-chat

2023-05-25 09:21 UTC, sostene12 approved these changes

2023-05-27 14:50 UTC, chrill-christella approved these changes

2023-05-27 17:49 UTC, sostene12 requested changes
<img width="1274" alt="Screenshot 2023-05-27 at 19 47 45" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/88575509/71fb08f1-83f8-4762-8fb4-a2c55c3985b9">

great job, can you try to make those select the same as that from the user account

2023-05-28 04:49 UTC, sostene12 approved these changes

2023-05-28 09:17 UTC, Shumba250 approved these changes
Fix login with google, it seems not to be working

2023-05-28 18:54 UTC, merged