Fix seller view product
atlp-rwanda/ecommerce-app-champions-fe pull request #48
Opened 2023-05-25 04:33 UTC by Luciefifi

# what does this PR do?
implement the frontend for a seller to view production in his/her collection
implement the frontend for a seller to view specific items
# Description of the task to be completed
implement the products component
implement single seller  product component
# How could this be manually tested
clone the repo's URL
checkout to fix-seller-view-product
run npm run dev
login as a vendor
create products if you do not have any
click on an eye icon to view details of the product

2023-05-26 13:03 UTC, sostene12 requested changes
<img width="1280" alt="Screenshot 2023-05-26 at 15 02 09" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/88575509/9f0c0dbf-02e4-481d-bc69-77bdd12de0f8">

there is a popup error when i click eneble or disable

2023-05-27 17:40 UTC, sostene12 requested changes
<img width="912" alt="Screenshot 2023-05-27 at 19 38 16" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/88575509/ea94858d-555b-4aad-a308-2c9df22c68dc">

correct that styles of that icons, it's better if they are all on the same line

<img width="1076" alt="Screenshot 2023-05-27 at 19 39 28" src="https://github.com/atlp-rwanda/ecommerce-app-champions-fe/assets/88575509/35295416-4afb-441d-823a-d4aa5ec9b5ef">

enable button is needed as well, and needs to be integrated. and also it is better to see in the description if the product is enabled or disabled

2023-05-27 19:22 UTC, oliviertech212 approved these changes

2023-05-28 09:12 UTC, Shumba250 approved these changes

2023-05-29 09:18 UTC, sostene12 approved these changes

2023-05-29 09:22 UTC, wakaflorien approved these changes

2023-05-29 09:23 UTC, merged