#67 feature: Users should be able Signup/Register to the E-commerce App and verify email
atlp-rwanda/ecommerce-app-champions-fe pull request #9
Opened 2023-04-25 15:13 UTC by sostene12

#### What does this PR do?
- user signup with email and password
#### Description of Task to be completed
- implement signup/register of the user
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ft-signup
- create .env file  and paste variables from .env.example
- run `npm run dev`
- navigate to the vendor for vendor signup or buyer for buyer signup
#### What are the relevant pivotal tracker stories?
- ![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able Signup/Register to the E-commerce App and verify email](https://trello.com/c/gJH8dzJ0)

2023-04-25 15:17 UTC, sostene12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able Signup/Register to the E-commerce App and verify email](https://trello.com/c/gJH8dzJ0/67-users-should-be-able-signup-register-to-the-e-commerce-app-and-verify-email)

2023-04-30 10:28 UTC, wakaflorien requested changes

2023-04-30 10:28 UTC, wakaflorien commented on src/pages/VendorSignupPage.jsx
> +		}, 9000);
- Why wait all this seconds? redirect the user as soon as the request is successful.

2023-05-01 08:52 UTC, wakaflorien approved these changes

2023-05-01 08:56 UTC, oliviertech212 approved these changes

2023-05-01 16:03 UTC, chrill-christella approved these changes

2023-05-01 16:46 UTC, Shumba250 approved these changes

2023-05-01 19:53 UTC, merged

2023-05-01 20:03 UTC, nicele08 requested changes
Ignore coverage folder and work on the comments, let me know when you're done.

2023-05-01 20:03 UTC, nicele08 commented on coverage/api/index.html
Add `coverage `folder in .gitignore

2023-05-01 20:03 UTC, nicele08 commented on src/redux/reducers/auth/authSlice.js
> +	error: '',
Use `null` instead of empty string as initial state

2023-05-01 20:03 UTC, nicele08 commented on src/redux/reducers/auth/authSlice.js
> +	user: '',
Same as here; I think initially user data should be `null` not empty string.

2023-05-01 20:03 UTC, nicele08 commented on src/redux/reducers/auth/authSlice.js
> +			state.error = '';
Then here you should reset error to `null` once a user registered successfully.

2023-05-01 20:03 UTC, nicele08 commented on src/redux/reducers/auth/authSlice.js
> +			state.user = '';
And here reset user to `null`

2023-05-01 20:03 UTC, nicele08 commented on src/redux/actions/auth.action.js
> +		}
I recommend you to use Async Action with createAsyncThunk, instead of dispatching on every action. You can read more [here](https://jasonwatmore.com/post/2022/06/21/react-redux-http-post-request-in-async-action-with-createasyncthunk) or [here](https://redux-toolkit.js.org/api/createAsyncThunk)

2023-05-01 20:03 UTC, nicele08 commented on src/pages/VendorSignupPage.jsx
> +						))}
Can we create a custom component for VendorSignupFields? Let's try to make reusable components wherever possible.

2023-05-01 20:03 UTC, nicele08 commented on src/pages/VendorSignupPage.jsx
> +		setSignupState({ ...signupState, [e.target.id]: e.target.value });
Please let's use functional form while updating state as it is a safer and more reliable way to update state.

Hint:
```javascript
setState(prevState => ({
...prevState,
property: newValue,
otherProperty: otherNewValue
))
```

2023-05-01 20:03 UTC, nicele08 commented on src/pages/BuyerSignupPage.jsx
> +						))}
Let's create a custom component for this so that we can use it somewhere else.

2023-05-01 20:03 UTC, nicele08 commented on src/pages/BuyerSignupPage.jsx
> +		setSignupState({ ...signupState, [e.target.id]: e.target.value });
Please let's use functional form while updating state as it is a safer and more reliable way to update state.

Hint:
```javascript
setState(prevState => ({
...prevState,
property: newValue,
})
```

2023-05-01 20:03 UTC, nicele08 commented on src/components/product/ProductList.jsx
> +					{products?.items?.map((item) => (
Better if we create a custom component that accept products and and render the ProductCards. It'll help to use it  on other pages.

2023-05-01 20:03 UTC, nicele08 commented on src/components/LoadingSpinner.jsx
> +
Let's avoid using external libraries for things we can implement ourselves. Why can't we use tailwindcss to have these spinners?

[Reference one](https://tailwindcss.com/docs/animation)
[Reference two](https://tailwind-elements.com/docs/standard/components/spinners/)

2023-05-01 20:03 UTC, nicele08 commented on src/components/Header.jsx
> +			</Link>
You can use the map() method to render the Link components dynamically based on an array of objects representing the links.

2023-05-01 20:03 UTC, nicele08 commented on src/components/Auth/InputError.jsx
> +export default InputError;
Define prop types and give default props here.

2023-05-01 20:03 UTC, nicele08 commented on src/components/Auth/Input.jsx
> +}) => {
Define prop types and give default props

2023-05-01 20:03 UTC, nicele08 commented on src/App.jsx
> +				<Route exact path="/" element={<HomePage />} />
`exact` is remove from recent versions of `react-router-dom`

2023-05-01 20:03 UTC, nicele08 commented on package.json
> +		"react-spinners": "^0.13.8",
You can remove this package. Let's only use packages for things we can't implement ourselves.